#!/bin/bash

usage="Usage: ./screenshot [-h] -b BROWSER -p PATH -u URL

Required arguments:
  -b  Browser to open screenshot in.
  -p  Path to copy screenshot to (eg. /var/www/html or myhost:html/).
  -u  URL where screenshot can be accessed.
  -r  Remove file from /tmp after it's been uploaded.
  -h  Print this help message.

Examples:
./screenshot -b google-chrome -p myhost:html/shots -u http://mydomain.com/shots
./screenshot -b google-chrome -p /var/www/html/shots -u file:///var/www/html/shots
"

while getopts "b:p:u:hr" options; do
    case $options in
        b)
            browser=$OPTARG
            ;;
        p)
            path=$OPTARG
            ;;
        u)
            url=$OPTARG
            ;;
        r)
            remove=1
            ;;
        h)
            echo "$usage"
            ;;
        *)
            echo "$usage"
            ;;
    esac
done

if [[ -z $browser || -z $path || -z $url ]]; then
    echo "$usage"
    exit 1
fi

# This is needed when using scrot's --select option
sleep 0.2

# Capture the screenshot & store the filename
scrot -s '%Y-%m-%d-%H%M%S_$wx$h.png' -e 'mv $f /tmp && echo $f > /tmp/last-shot' || exit 1

# Read the filename into a variable
last_shot=$(cat /tmp/last-shot)

# Copy the file to the provided path
scp "/tmp/${last_shot}" "$path" || exit 1

# Clean up
if [[ "$remove" -eq 1 ]]; then
    rm -f "/tmp/${last_shot}"
fi

# Open the image in the browser
"$browser" "${url}/${last_shot}"
